name: 'Source code analyzer'
description: 'Analyze source code quality'
inputs:
  github-username:
    description: 'Path to file'
    required: true
  project-name:
    description: 'Project Name'
    required: true
  commit-sha:
    description: 'Commit hash'
    required: true
  url:
    description: 'Url for upload'
    required: true
  token:
    description: 'authentication token to send package'
    required: true
outputs:
  result:
    description: 'Source code result JSON as a base64 format'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-username }}
    - ${{ inputs.project-name }}
    - ${{ inputs.commit-sha }}
    - ${{ inputs.url }}
    - ${{ inputs.token }}
  